spring:
  application:
    name: shopping-plugin-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopping_plugin}
    username: ${DB_USERNAME:shopping_plugin}
    password: ${DB_PASSWORD:shopping_plugin}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
